spring:
  application:
    name: kiwifruit
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/kiwifruit
    username: postgres
    password: Mars123456
    driver-class-name: org.postgresql.Driver
bill:
  path: /Users/djming/devData/kiwifruit/import/